root_diamoons_band_accounting_homepage:
    path:     /
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:index }

root_diamoons_band_accounting_activity_list:
    path:     /activities
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:list }
    methods: [GET]

root_diamoons_band_accounting_activity_create:
    path:     /activities
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:create }
    methods: [POST]

root_diamoons_band_accounting_activity_update:
    path:     /activities/{id}
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:update }
    methods: [PUT]