root_diamoons_band_accounting_homepage:
    path:     /
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:index }

root_diamoons_band_accounting_activity:
    path:     /activity/{id}
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:get }
    requirements: {id: \d+}

root_diamoons_band_accounting_activity_list:
    path:     /activity/list
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:list }

root_diamoons_band_accounting_activity_create:
    path:     /activity/new
    defaults: { _controller: RootDiamoonsBandAccountingBundle:Activity:create }
    requirements: { _method: post }